import type { Metadata } from "next";
import "./globals.css";

import { Fira_Code } from 'next/font/google';
import { Roboto } from 'next/font/google';

const firaCode = Fira_Code({
  subsets: ['latin'],
  weight: "300",
  variable: '--font-fira-code',
});

const init_roboto = Roboto({
  subsets: ['latin'],
  weight: ['100','300'],
  variable: '--font-fira-code',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} ${init_roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
